name: build-master
on:
  push:
    branches:
      - '**'
  pull_request: {}
  schedule:
    - cron: 0 4 * * *

jobs:
  validate_and_test_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check *.zig src/*.zig
      - run: zig build
      - run: zig build test
  validate_and_test_011:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig fmt --check *.zig src/*.zig
      - run: zig build
      - run: zig build test
