name: run-tests
on:
  push:
    branches:
      - '**'
  pull_request: {}
  schedule:
    - cron: 0 4 * * 2

jobs:
  validate_and_test_010:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.1
      - run: zig fmt --check *.zig src/*.zig
      - run: zig build test

  validate_and_test_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check *.zig src/*.zig
      - run: zig build test
